"""Assemble all four deliverables into a single self-contained Markdown report."""
from ..models import AnalysisResult

_SEV_LABEL = {"high": "HIGH", "mid": "MID", "low": "LOW", "info": "INFO"}


def _md_escape(text: str) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def to_markdown(r: AnalysisResult) -> str:
    names = {s.id: s.name for s in r.screens}
    lines: list[str] = []
    add = lines.append

    add("# User Flow 분석 보고서")
    add("")
    add(f"- **영상**: {r.video_name}")
    add(f"- **길이**: {r.duration:.0f}초")
    add(f"- **요약**: 고유 화면 {len(r.screens)}개 · 화면 전환 {len(r.transitions)}회 · "
        f"진단 {len(r.findings)}건")
    add("")

    add("## 1. 화면 흐름도")
    add("")
    add("```mermaid")
    add(r.mermaid)
    add("```")
    add("")
    add("> 점선 = 백트래킹(앞으로 갔다가 되돌아온 이동). "
        "시트/모달의 열기·닫기 왕복은 점선에서 제외됩니다.")
    add("")

    add(f"## 2. 화면 인벤토리 — {len(r.screens)}개")
    add("")
    add("| ID | 화면명 | 유형 | 주요 UI 요소 | 등장 시각 |")
    add("|---|---|---|---|---|")
    for s in r.screens:
        appear = ", ".join(f"{t:.0f}s" for t in s.appearances[:8])
        if len(s.appearances) > 8:
            appear += f" 외 {len(s.appearances) - 8}회"
        add(f"| {s.id} | {_md_escape(s.name)} | {s.type} | "
            f"{_md_escape(' · '.join(s.elements))} | {appear} |")
    add("")

    add(f"## 3. 행동 로그 — {len(r.events)}개 이벤트")
    add("")
    add("| 시각 | 화면 | 행동 | 대상 | 비고 |")
    add("|---|---|---|---|---|")
    for e in r.events:
        action = e.action + (" *" if e.confidence == "estimated" else "")
        add(f"| {e.timestamp:.1f}s | {_md_escape(names.get(e.screen_id, e.screen_id))} | "
            f"{action} | {_md_escape(e.target)} | {_md_escape(e.note)} |")
    add("")
    add("\\* = 추정된 행동")
    add("")

    add(f"## 4. UX 진단 — {len(r.findings)}건")
    add("")
    if not r.findings:
        add("발견된 문제 없음.")
    for f in r.findings:
        add(f"### [{_SEV_LABEL[f.severity]}] {f.title}")
        add("")
        add(f"- 근거: {f.evidence}")
        if f.timestamps:
            add("- 관련 시각: " + ", ".join(f"{t:.0f}s" for t in f.timestamps))
        if f.suggestion:
            add(f"- 제안: {f.suggestion}")
        add("")
    add("---")
    add("*단일 영상(n=1) 기반 진단으로, 일반화 전 추가 검증이 필요합니다. "
        "Generated by [User Flow Analyzer](https://github.com/HXRHIT/user-flow-analyzer).*")
    return "\n".join(lines)
